FROM --platform=amd64 pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel

ENV PLATFORM=cpu

WORKDIR /app

RUN pip install \
    jax[cuda] \
    numpyro[cuda] \
    pandas \
    -f https://storage.googleapis.com/jax-releases/jax_releases.html

COPY . .